### ISSUE TITLE
NOAA API forecast endpoint now requires grids

### ISSUE THREAD

**Issue by dareno** [thomp/noaa.el#8]
This line seems to reference an old forecast endpoint which would operate on lat/long. It now seems to require resolution from lat/long to a grid:
Here's the code line in question: https://github.com/thomp/noaa/blob/master/noaa.el#L452

The error returned from NOAA is 
`'/points/36.7478,-119.771/forecast' is not a valid resource path`

More documentation on the NOAA API:
https://www.weather.gov/documentation/services-web-api?prevfmt=application%2Fcap%2Bxml&prevopt=area%3DMN

**Comment by thomp** [comment]
Thank you for the nudge on this. I've taken out a bit of cruft and added a means of mapping latitude/longitude pairs to forecast URLs based on the gridpoints API. This doesn't address the issue you raise directly, but it sets the groundwork for working with the new API.

https://github.com/thomp/noaa/commit/c5c07dfb63077dcb8bcfd8ef539eb0364083e629

https://github.com/thomp/noaa/commit/4db6775a42d07d28191c3cf6c4c5aaca3415689a

https://github.com/thomp/noaa/commit/bfa7b2f9abcc7a18472c6998634450c876900170

https://github.com/thomp/noaa/commit/e0d47e8fe62f40487ecf8d2d78a634a966bb1049

When I have a spare moment, I hope to return to this and get things in place for using the correct URLs for forecast retrieval.

**Comment by thomp** [comment]
I believe commit https://github.com/thomp/noaa/commit/d0c0c6a311591df94c6580ba634c0ed0c20bd85d is the last piece needed to resolve the issue.
Please reopen the issue, or open a new issue, if this isn't the case.

**Comment by gvoysey** [comment]
`'/points/40.71,-74.0/forecast/hourly' is not a valid resource path`  -- seems related; when pressing `h` in the main noaa buffer.  The rest seems to work now!

```symbol-status: error 
E Error response: (error http 404) 
response: #s(request-response 404 nil "{
    \"correlationId\": \"745c3e5b\",
    \"title\": \"Not Found\",
    \"type\": \"https://api.weather.gov/problems/NotFound\",
    \"status\": 404,
    \"detail\": \"'/points/40.71,-74.0/forecast/hourly' is not a valid resource path\",
    \"instance\": \"https://api.weather.gov/requests/745c3e5b\"
}" (error http 404) error "https://api.weather.gov/points/40.71,-74.0/forecast/hourly" nil (:headers (("Upgrade-Insecure-Requests" . "1") ("User-Agent" string-trim (url-http-user-agent-string))) :parser buffer-string :error noaa-http-error-callback :status-code ((404 . noaa--api-weather-gov--4nn-callback) (500 lambda (&rest x) (message "%S" x) (message "Got 500 -- the server seems unhappy")) (503 lambda (&rest x) (message "%s" "Service Unavailable (503)"))) :success noaa-http-callback-hourly :url "https://api.weather.gov/points/40.71,-74.0/forecast/hourly" :response #0 :encoding utf-8) #<killed buffer> "HTTP/2 404 ``` 

appears in the `*Messages*` buffer.  (the lat/long is new york city, but it seems to raise for other locations too)

**Comment by thomp** [comment]
Thank you. 1ebacdfbaa996319adf88a49258814c28ba49b1b and 63636dbe7fb84861bb46f3cc8eac6de5f4060e91 transition queries for the hourly forecast to the newer gridpoints API. Hopefully this resolves the issue.
